# Generated by Django 4.2.14 on 2024-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='operation',
            field=models.CharField(default='old', max_length=10),
            preserve_default=False,
        ),
    ]
